repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.85.0"
    hooks:
      - id: terraform_fmt
        files: ^infrastructure/
      - id: terraform_validate
        files: ^infrastructure/
      - id: terraform_tflint
        files: ^infrastructure/
      - id: terraform_docs
        files: ^infrastructure/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
